config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :players

  unauthenticated do
    root to: 'pages#home'
  end

  authenticated do
    root to: 'pages#dashboard', as: 'dashboard'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :trainings

  validates :name, presence: true
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :results, dependent: :destroy
  has_many :trainings, through: :results
  has_one_attached :photo

  validates :name, :email, :encrypted_password, presence: true
  validates :email, format: { with: Devise.email_regexp }
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :training
  belongs_to :player
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :category
  has_many :results
  has_many :players, through: :results

  validates :name, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_player!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_player!, only: :home

  def home; end

  def dashboard; end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
  def avatar_for(player)
    @avatar = player.photo.key
    if @avatar.empty?
      image_tag('avatar-default.svg', crop: :fit, alt: "#{player.name}'s avatar picture")
    else
      cl_image_tag(@avatar, crop: :fit, alt: "#{player.name}'s avatar picture")
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moiminteam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= favicon_link_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class='container-home'>
  <h1>Welcome to your dashboard, <%= current_player.name %></h1>
  <div class='avatar'>
    <%= avatar_for(current_player) %>
  </div>
</div>

app/views/pages/home.html.erb
<div class='container-home'>
  <h1>Keep the<br>móiminteam.</h1>
  <h2>Sign in for more.</h2>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div>
    <%= link_to image_tag("belgium-gaa-logo.svg", alt: "Belgium GAA Logo", class: "logo-footer"), root_path %>
    <p>Developed for Belgium Gaelic Games - 2021</p>
  </div>
  <div class="footer-links">
    <a href="https://github.com/margaux-m/moiminteam" target="_blank">
      <%= image_tag("icon-github.svg", class: "footer-link") %>
      <%= image_tag("icon-github-white.svg", class: "footer-link-hover") %>
    </a>
    <a href="https://www.margauxmansanarez.com" target="_blank">
      <%= image_tag("icon-mm.svg", class: "footer-link") %>
      <%= image_tag("icon-mm-white.svg", class: "footer-link-hover") %>
    </a>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav>
  <h1><%= link_to 'móiminteam', root_path, id: "logo-navbar" %></h1>
  <% if player_signed_in? %>
    <%= link_to 'Sign out', destroy_player_session_path, :method => :delete, class: "btn btn-primary btn-outline btn-outline-black" %>
  <% else %>
    <%= link_to 'Sign in', player_session_path, class: "btn btn-primary btn-black" %>
  <% end %>
</nav>